#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const frontendRoot = resolve(here, "..");

const defaultOutDir = resolve(
  frontendRoot,
  "../primora-backend/contracts/out",
);
const outDir = process.env.CONTRACTS_OUT_DIR
  ? resolve(process.env.CONTRACTS_OUT_DIR)
  : defaultOutDir;

const abisDir = join(frontendRoot, "lib", "abis");

const contracts = [
  "PrimToken",
  "Treasury",
  "MiningContract",
  "OracleAggregator",
  "StakingContract",
  "NodeRegistry",
  "HouseEdge",
];

const camel = (name) => name.charAt(0).toLowerCase() + name.slice(1);

mkdirSync(abisDir, { recursive: true });

const generated = [];
for (const name of contracts) {
  const jsonPath = join(outDir, `${name}.sol`, `${name}.json`);
  let artifact;
  try {
    artifact = JSON.parse(readFileSync(jsonPath, "utf8"));
  } catch (err) {
    console.error(`ERROR: could not read ${jsonPath}: ${err.message}`);
    console.error("Run `forge build` in the backend contracts dir first.");
    process.exit(1);
  }
  if (!Array.isArray(artifact.abi)) {
    console.error(`ERROR: no abi array in ${jsonPath}`);
    process.exit(1);
  }

  const exportName = `${camel(name)}Abi`;
  const body = `// Generated by scripts/extract-abis.mjs -- do not edit by hand.
// Re-run \`node scripts/extract-abis.mjs\` after rebuilding the contracts.
export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
  const target = join(abisDir, `${name}.ts`);
  writeFileSync(target, body);
  generated.push(`lib/abis/${name}.ts (${exportName}, ${artifact.abi.length} entries)`);
}

const indexBody = `// Generated by scripts/extract-abis.mjs -- do not edit by hand.
${contracts.map((n) => `export { ${camel(n)}Abi } from "./${n}";`).join("\n")}
`;
writeFileSync(join(abisDir, "index.ts"), indexBody);
generated.push("lib/abis/index.ts (barrel)");

console.log(`Source out dir: ${outDir}`);
console.log("Generated:");
for (const line of generated) console.log(`  ${line}`);
